---
title: 代码输出题
order: 23
category:
  - 面试
  - 代码输出提
---

## this 指向

```js
var name = "123";
var obj = {
  name: "456",
  getName: function () {
    function printName() {
      console.log(this.name);
    }
    printName();
  },
};

obj.getName();
```

输出:123

解析：只有直接作为对象方法调用的普通函数的 this 才指向对象，printName 是一个普通函数调用，this 指向 window

```js
var name = "123";
var obj = {
  name: "456",
  getName: function () {
    const printName = () => {
      console.log(this.name);
    };
    printName();
  },
};

const fn = obj.getName;
fn();
```

输出：123

## 原型链

```js
Function.prototype.a = () => console.log("a");
Object.prototype.b = () => console.log("b");

const func = function () {};
const a = new func();
func.a();
a.a();
a.b();
```

输出：

1. func.a()可以正常打印
2. a.a()报错，无法访问到 a.a

解析：
原型链：

1. func->Function.prototype->Object.prototype
2. a->func.prototype->Object.prototype

## 作用域链

```js
var count = 20;
function a() {
  return count + 10;
}
function b() {
  var count = 20;
  return a();
}
console.log(b());
```

输出：30
解析：作用域链在函数定义时就确定了

## 变量提升

```js
var a = 20;
function b() {
  console.log(a);
  var a = 10;
}
b();
```

输出：undefined
解析：var 定义的变量存在变量提升，提升到局部作用域的顶部，此时还是 undefined

```js
var a = 20;
function b() {
  console.log(a);
  let a = 10;
}
b();
```

输出：报错
解析：在 let 或 const 变量的作用域内，尝试在它们的声明之前访问它们时会进入暂时性死区 (TDZ)。局部变量 a 在 console.log(a); 之前还未被初始化，因此 JavaScript 引擎会抛出 ReferenceError，而不会使用全局的 a。

## promise 链条

```js
Promise.reject(1)
  .then((val) => 0)
  .then(
    (val) => console.log(val),
    (reason) => console.log(reason)
  );
```

输出：1
解析：透传
